package com.example.demo.controller.api;
import com.example.demo.model.*;import com.example.demo.service.*;import io.swagger.v3.oas.annotations.*;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import io.swagger.v3.oas.annotations.tags.Tag;import jakarta.validation.Valid;import java.util.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") @Tag(name="Каталог",description="CRUD товаров, категорий и производителей") public class CatalogApiController {
 private final CategoryService categories;private final ManufacturerService manufacturers;private final ProductService products;
 public CatalogApiController(CategoryService c,ManufacturerService m,ProductService p){categories=c;manufacturers=m;products=p;}
 @GetMapping("/categories")@Operation(summary="Список категорий")List<Category> categories(@RequestParam(required=false)String q){return categories.search(q);}
 @GetMapping("/categories/{id}")@Operation(summary="Категория по ID")Category category(@PathVariable Long id){return categories.findById(id).orElseThrow();}
 @PostMapping("/categories")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Создать категорию")Category addCategory(@Valid @RequestBody Category v){v.setId(null);return categories.save(v);}
 @PutMapping("/categories/{id}")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Изменить категорию")Category editCategory(@PathVariable Long id,@Valid @RequestBody Category v){categories.findById(id).orElseThrow();v.setId(id);return categories.save(v);}
 @DeleteMapping("/categories/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)@PreAuthorize("hasRole('ADMIN')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Удалить категорию")void deleteCategory(@PathVariable Long id){categories.delete(id);}
 @GetMapping("/manufacturers")@Operation(summary="Список производителей")List<Manufacturer> manufacturers(@RequestParam(required=false)String q){return manufacturers.search(q);}
 @GetMapping("/manufacturers/{id}")@Operation(summary="Производитель по ID")Manufacturer manufacturer(@PathVariable Long id){return manufacturers.findById(id).orElseThrow();}
 @PostMapping("/manufacturers")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Создать производителя")Manufacturer addManufacturer(@Valid @RequestBody Manufacturer v){v.setId(null);return manufacturers.save(v);}
 @PutMapping("/manufacturers/{id}")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Изменить производителя")Manufacturer editManufacturer(@PathVariable Long id,@Valid @RequestBody Manufacturer v){manufacturers.findById(id).orElseThrow();v.setId(id);return manufacturers.save(v);}
 @DeleteMapping("/manufacturers/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)@PreAuthorize("hasRole('ADMIN')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Удалить производителя")void deleteManufacturer(@PathVariable Long id){manufacturers.delete(id);}
 @GetMapping("/products")@Operation(summary="Список и поиск товаров")List<Product> products(@RequestParam(required=false)String q){return products.search(q);}
 @GetMapping("/products/{id}")@Operation(summary="Товар по ID")Product product(@PathVariable Long id){return products.findById(id).orElseThrow();}
 @PostMapping("/products")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Создать товар",description="category и manufacturer передаются объектами с заполненным id")Product addProduct(@Valid @RequestBody Product v){v.setId(null);return products.save(v);}
 @PutMapping("/products/{id}")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Изменить товар")Product editProduct(@PathVariable Long id,@Valid @RequestBody Product v){products.findById(id).orElseThrow();v.setId(id);return products.save(v);}
 @DeleteMapping("/products/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)@PreAuthorize("hasRole('ADMIN')")@SecurityRequirement(name="bearerAuth")@Operation(summary="Удалить товар")void deleteProduct(@PathVariable Long id){products.delete(id);}
}
