package com.example.demo.controller.api;
import com.example.demo.model.*;import com.example.demo.service.*;import io.swagger.v3.oas.annotations.*;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import io.swagger.v3.oas.annotations.tags.Tag;import jakarta.validation.Valid;import java.util.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") @SecurityRequirement(name="bearerAuth") @Tag(name="Заказы",description="CRUD заказов и их позиций") public class OrderApiController {private final OrderService orders;private final OrderItemService items;public OrderApiController(OrderService o,OrderItemService i){orders=o;items=i;}
 @GetMapping("/orders")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Список заказов")List<Order> allOrders(@RequestParam(required=false)String q){return orders.search(q);}
 @GetMapping("/orders/{id}")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Заказ по ID")Order order(@PathVariable Long id){return orders.findById(id).orElseThrow();}
 @PostMapping("/orders")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Создать заказ")Order addOrder(@Valid @RequestBody Order v){v.setId(null);return orders.save(v);}
 @PutMapping("/orders/{id}")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Изменить заказ")Order editOrder(@PathVariable Long id,@Valid @RequestBody Order v){orders.findById(id).orElseThrow();v.setId(id);return orders.save(v);}
 @DeleteMapping("/orders/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)@PreAuthorize("hasRole('ADMIN')")@Operation(summary="Удалить заказ")void deleteOrder(@PathVariable Long id){orders.delete(id);}
 @GetMapping("/order-items")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Список позиций заказов")List<OrderItem> allItems(@RequestParam(required=false)String q){return items.search(q);}
 @GetMapping("/order-items/{id}")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Позиция по ID")OrderItem item(@PathVariable Long id){return items.findById(id).orElseThrow();}
 @PostMapping("/order-items")@ResponseStatus(HttpStatus.CREATED)@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Создать позицию заказа")OrderItem addItem(@Valid @RequestBody OrderItem v){v.setId(null);return items.save(v);}
 @PutMapping("/order-items/{id}")@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Изменить позицию заказа")OrderItem editItem(@PathVariable Long id,@Valid @RequestBody OrderItem v){items.findById(id).orElseThrow();v.setId(id);return items.save(v);}
 @DeleteMapping("/order-items/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)@PreAuthorize("hasAnyRole('ADMIN','PHARMACIST')")@Operation(summary="Удалить позицию")void deleteItem(@PathVariable Long id){items.delete(id);}
}
