package com.example.demo.service;
import com.example.demo.model.*;import com.example.demo.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;
@Service public class CartService {private final UserRepository users;private final ProductRepository products;private final OrderRepository orders;private final OrderItemRepository items;
 public CartService(UserRepository u,ProductRepository p,OrderRepository o,OrderItemRepository i){users=u;products=p;orders=o;items=i;}
 public Order getCart(String username){User u=users.findByUsername(username).orElseThrow();return orders.findFirstByUserIdAndStatus(u.getId(),OrderStatus.NEW).orElseGet(()->{Order o=new Order();o.setUser(u);return orders.save(o);});}
 @Transactional public void add(String username,Long productId,int quantity){if(quantity<1)throw new IllegalArgumentException("Количество должно быть положительным");Order o=getCart(username);Product p=products.findById(productId).orElseThrow(()->new IllegalArgumentException("Товар не найден"));OrderItem i=items.findByOrderIdAndProductId(o.getId(),productId).orElseGet(OrderItem::new);int total=(i.getId()==null?0:i.getQuantity())+quantity;if(total>p.getStockQuantity())throw new IllegalArgumentException("Недостаточно товара на складе");i.setOrder(o);i.setProduct(p);i.setQuantity(total);if(i.getId()==null)i.setPriceAtPurchase(p.getPrice());items.save(i);recalculate(o);}
 @Transactional public void update(String username,Long itemId,int quantity){Order o=getCart(username);OrderItem i=items.findById(itemId).orElseThrow();if(!i.getOrder().getId().equals(o.getId()))throw new SecurityException("Чужая корзина");if(quantity<=0){items.delete(i);}else{if(quantity>i.getProduct().getStockQuantity())throw new IllegalArgumentException("Недостаточно товара");i.setQuantity(quantity);items.save(i);}recalculate(o);}
 @Transactional public Order checkout(String username){Order o=getCart(username);var list=items.findByOrderId(o.getId());if(list.isEmpty())throw new IllegalStateException("Корзина пуста");for(OrderItem i:list)if(i.getQuantity()>i.getProduct().getStockQuantity())throw new IllegalStateException("Недостаточно товара: "+i.getProduct().getTitle());for(OrderItem i:list){Product p=i.getProduct();p.setStockQuantity(p.getStockQuantity()-i.getQuantity());products.save(p);}recalculate(o);o.setStatus(OrderStatus.PAID);return orders.save(o);}
 private void recalculate(Order o){BigDecimal sum=items.findByOrderId(o.getId()).stream().map(i->i.getPriceAtPurchase().multiply(BigDecimal.valueOf(i.getQuantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);o.setTotalAmount(sum);orders.save(o);}
}
